# Generated by Django 5.0.6 on 2024-06-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('write_here', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'portfolio_table',
            },
        ),
    ]
